version: '2'
services:
    ccmanager-app:
        image: ccmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ccmanager-mysql:3306/ccmanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ccmanager-mysql:
        extends:
            file: mysql.yml
            service: ccmanager-mysql
